### PR TITLE
Added DSA CODES WITH C++ .

### PR DESCRIPTION
**Pull request by aaryansood2512**
Hello Sir,
I have added DSA codes to your repository kindly check.
Hope! you will merge it.🥰

### CODE REVIEW

**Comment by rishabhhandoo** [comment]
thank you for contributing 
have fun at hacktoberfest

**Comment by aaryansood2512** [comment]
Sure Sir
You too

**Comment by aaryansood2512** [comment]
Can I push more in your repo?

**Comment by rishabhhandoo** [comment]
yeah sure

**Comment by aaryansood2512** [comment]
Awesome, thanks!

**Comment by aaryansood2512** [comment]
Hey, I have added more codes to you repo
Hope, You merge them.
Happy #Hactoberfest

**Pull request merged**
